### ISSUE TITLE
xbox symbol detection

### ISSUE THREAD

**Issue by medievil1** [mborgerson/ghidra-xbe#13]
ummm perhaps it is something I am doing incorrectly or misunderstand?? I thought the xbe extension should replace function with their correct names as they are detected? I am not experiencing that, I just get

uint FUN_00011000(undefined4 *param_1,undefined4 *param_2)

{
  int iVar1;
  
  iVar1 = __stricmp(*param_1,*param_2);
  return (uint)(iVar1 == 0);
}

**Comment by gandalfthewhite19890404** [comment]
Do you using Windows?
I guess - it happens because of this:
File of cli-tool located in GHIDRA_ROOT\Ghidra\Extensions\ghidra-xbe\os\win64 named as XbSymbolDatabaseTool.
It is without extension so it cannot be executed. And if you rename it to exe, ghidra throws error - XbSymbolDatabase not found.

Why Application.getOSFile("XbSymbolDatabaseTool").getAbsolutePath() does not return name with extension?

**Comment by RadWolfie** [comment]
Main problem is `exec.waitFor();` cause deadlock when input stream is full and waiting to be flush. I will make a pull request to resolve this issue soon.

**Comment by RadWolfie** [comment]
This issue is resolved in pull request #16.
